specs
css
	^ String space join:
'.c0 { color:#222 }
.c1 { color:#eaeaea }
.c2 { color:#888 }
.c3 { color:#666 }
.c4 { color:#444 }
.c5 { color:#393 }
.c6 { color:#363 }
body { text-align:center; font-size:1.3em; font-family:sans-serif; background-color:#222; color:#eaeaea }
.main { max-width:450px; margin-left:auto; margin-right:auto }
a:link, a:visited, a:active, a:hover { color:inherit; text-decoration:none }
em.subtitle { font-variant:small-caps }
p.menu { font-variant:small-caps }
dl.details { text-align:left; max-width:350px; margin-left:auto; margin-right:auto }
dl.settings { max-width:275px }
dl.details > dt { float:left; clear:left; width:100px; text-align:right; color:#666; font-size:0.75em; margin-top:4px }
dl.details > dt:after { content:":" }
dl.details > dd { margin: 0 0 0 105px }
ul.library { text-align:left; list-style-type: square }
ul.library > li { min-height:1.75em; margin-bottom:8px }
ol.playlist { text-align:left }
ol.playlist > li { margin-bottom:8px }
.c-title { font-weight:bold; font-size:1.5em }
.c-title-c { font-weight:bold }
.c-album { font-style:italic; font-size:1.4em }
.c-album-c { font-style:italic }
.c-artist { font-size: 1.3em }
.c-artist-c { }
.l1 { }
.l2 { font-size:0.75em; font-style:italic }
.l3 { font-size:0.75em }
.progress { font-family:monospace }
.tab { }
.tab-selected { font-weight:bold }
' lines